language: python
python: "3.6"
addons:
  apt:
    packages:
      - sshpass
install:
  - pipenv --python 3 install --system --deploy
script:
  - gunicorn --bind 0.0.0.0:5000 wsgi:app &
after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
